// Test generated by RoostGPT for test GoFinanceTest1 using AI Model gpt

package util

import (
	"math/rand"
	"testing"
	"time"
)

func TestRandomStringae0b4ebc4c(t *testing.T) {
	rand.Seed(time.Now().UnixNano())

	t.Run("Test with positive number", func(t *testing.T) {
		number := 5
		result := RandomString(number)
		if len(result) != number {
			t.Errorf("Expected length %d but got %d", number, len(result))
		}
	})

	t.Run("Test with zero", func(t *testing.T) {
		number := 0
		result := RandomString(number)
		if len(result) != number {
			t.Errorf("Expected length %d but got %d", number, len(result))
		}
	})

	t.Run("Test with negative number", func(t *testing.T) {
		number := -5
		result := RandomString(number)
		if len(result) != 0 {
			t.Errorf("Expected length 0 but got %d", len(result))
		}
	})
}
