// Test generated by RoostGPT for test GoFinanceTest1 using AI Model gpt

package util

import (
	"strings"
	"testing"
)

func TestRandomEmail9d35a21e5a(t *testing.T) {
	// Test for correct length
	email := RandomEmail(10)
	if len(email) != 21 {
		t.Errorf("Expected email of length 21, got %v", len(email))
	}

	// Test for correct domain
	splitEmail := strings.Split(email, "@")
	if splitEmail[1] != "email.com" {
		t.Errorf("Expected domain to be email.com, got %v", splitEmail[1])
	}

	// Test for random string of correct length
	if len(splitEmail[0]) != 10 {
		t.Errorf("Expected random string of length 10, got %v", len(splitEmail[0]))
	}

	// Test for non-unique emails
	email2 := RandomEmail(10)
	if email == email2 {
		t.Error("Expected different emails, got two identical")
	}
}
